import {
  heightPercentageToDP,
  widthPercentageToDP,
} from '../utils/DeviceResolution';

export const theme = {
  colors: {
    primary: '#11daae',
    orange: '#FF8200',
    background: '#3a3b45',

    text: '#838391',
    textSecondary: '#666666',
    danger: '#DC2626',
    dangerText: '#FF0000',
    secondary: '#5D4A99',
    red: '#FF1B3A',
    success: '#00CE75',
    blue: '#3D50DF',
    darkBlue: '#071C33',
    white: '#FFFFFF',
    bgBottomTab: '#E8EDF4',
    inactiveTab: '#66667B',
    infoCourse: '#ACACAC',
    titleCard: '#444444',
    description: '#5c5c5c',
    lightBlue: '#e3ebf3',
    moduleHeader: '#AFA4FF',
    textColor: '#838383',
    boxBackground: '#F1F1F1',
    subtitleColor: '#333333',
    colorArrowSecondary: '#5D4998',
    colorInput: '#828282',
    textExamination: '#5C5C5C',
    textExaminationSecondary: '#2B2B2B',
    border: '#C0C0C0',
    searchInputColor: '#DAE1ED',
    dotColor: '#E30613',
    dotColorSecondary: '#505050',
    analizing: '#ff8787',
  },
  shadow: {
    shadowOpacity: 0.5,
    shadowOffset: {width: 5, height: 3},
    shadowRadius: 2,
    elevation: 5,
    shadowColor: '#00000066',
  },
  device: {
    width: widthPercentageToDP('100%'),
    height: heightPercentageToDP('100%'),
  },
  spacings: {
    xxxsmall: '4px',
    xxsmall: '8px',
    xsmall: '12px',
    small: '14px',
    medium: '16px',
    large: '18px',
    xlarge: '20px',
    xxlarge: '24px',
    xxxlarge: '32px',
    xxxxlarge: '42px',
  },
  fontSizes: {
    xxsmall: '8px',
    xsmall: '12px',
    small: '14px',
    medium: '16px',
    large: '18px',
    xlarge: '20px',
    xxlarge: '24px',
    xxxlarge: '32px',
    xxxxlarge: '50px',
  },
  fontFamilies: {
    light: 'Poppins-Light',
    regular: 'Poppins-Regular',
    medium: 'Poppins-Medium',
    semiBold: 'Poppins-SemiBold',
    bold: 'Poppins-Bold',
  },
  fontWeights: {
    light: 300,
    regular: 400,
    medium: 500,
    semiBold: 600,
    bold: 700,
  },
};
